config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users, only: %i[index create]
  resources :animals, only: [:index] do
    member do
      post :like
      post :dislike
      post :reset
    end
  end
end

app/models/animal.rb
class Animal < ApplicationRecord

  def image_path
    "media/images/animal_icons/#{name}.svg"
  end

  def liked_by_user?(user:)
    user.liked_animals.include? self
  end

  def disliked_by_user?(user:)
    user.disliked_animals.include? self
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disliked_animals_user.rb
class DislikedAnimalsUser < ApplicationRecord
  belongs_to :animal
  belongs_to :user
end

app/models/liked_animals_user.rb
class LikedAnimalsUser < ApplicationRecord
  belongs_to :animal
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :liked_animals_users
  has_many :liked_animals, through: :liked_animals_users, source: :animal, class_name: 'Animal'

  has_many :disliked_animals_users
  has_many :disliked_animals, through: :disliked_animals_users, source: :animal, class_name: 'Animal'
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  include AnimalHelper
  def index
    if @current_user
      @animals = Animal.all
      @liked_animals = @current_user.liked_animals
      @disliked_animals = @current_user.disliked_animals
    else
      redirect_to :root_path
    end
  end

  def create
    @user = User.create(name: params.dig(:user, :name))
    session[:user_id] = @user.id if @user.save

    redirect_to root_path
  end

  def like
    @animal = Animal.find(params[:id])

    disliked_animals = DislikedAnimalsUser.find_by(user: @current_user, animal: @animal)
    disliked_animals&.destroy

    @current_user.liked_animals << @animal

    render json: {
      html: render_to_string(partial: 'animals/display', locals: { animal: @animal, user: @current_user})
    }
  end

  def reset
    @animal = Animal.find(params[:id])

    liked_animals = LikedAnimalsUser.find_by(user: @current_user, animal: @animal)
    liked_animals&.destroy

    disliked_animals = DislikedAnimalsUser.find_by(user: @current_user, animal: @animal)
    disliked_animals&.destroy

    render json: {
      html: render_to_string(partial: 'animals/display', locals: { animal: @animal, user: @current_user})
    }
  end

  def dislike
    @animal = Animal.find(params[:id])

    liked_animals = LikedAnimalsUser.find_by(user: @current_user, animal: @animal)
    liked_animals&.destroy

    @current_user.disliked_animals << @animal

    render json: {
      html: render_to_string(partial: 'animals/display', locals: { animal: @animal, user: @current_user})
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_current_user

  def fetch_current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def create
    @user = User.create(name: params.dig(:user, :name))
    session[:user_id] = @user.id if @user.save

    redirect_to root_path
  end
end

app/helpers/animal_helper.rb
module AnimalHelper
  def animal_display_class(animal:, user: nil)
    return 'colorize-blue' unless user

    if animal.liked_by_user?(user: user)
      'colorize-green'
    elsif animal.disliked_by_user?(user: user)
      'colorize-red'
    else
      'colorize-blue'
    end
  end
end

app/views/animals/_display.html.haml
.position-relative
  .position-absolute.top-0.end-0
    .hvr-icon-hang.text-primary
      %i.fas.fa-trash.hvr-icon{data: { action: 'click->likeit#reset' }  }
.animal_image.mb-3
  = image_pack_tag(animal.image_path, width: '250px', class: animal_display_class(animal: animal, user: user))
.position-relative
  - unless animal.liked_by_user?(user: user)
    .position-absolute.bottom-0.start-0{data: { action: 'click->likeit#like' }  }
      .hvr-icon-hang.text-success
        %i.fas.fa-2x.fa-thumbs-up.hvr-icon
  - unless animal.disliked_by_user?(user: user)
    .position-absolute.bottom-0.end-0{data: { action: 'click->likeit#dislike' } }
      .hvr-icon-hang.text-danger
        %i.fas.fa-2x.fa-thumbs-down.hvr-icon

app/views/animals/index.html.haml
.container
  .col-8
    %h1.display-3
      Hi #{@current_user.name}
    %p
      You like #{@liked_animals.pluck(:name).map(&:pluralize).to_sentence}
    %p
      You don't like #{@disliked_animals.pluck(:name).map(&:pluralize).to_sentence}
  .row
    - @animals.each do |animal|
      .col{data:
            {
              controller: 'likeit',
              likeit_likepath_value: like_animal_path(animal),
              likeit_dislikepath_value: dislike_animal_path(animal),
              likeit_resetpath_value: reset_animal_path(animal)
            }
        }
        .animal-icon.shadow.p-3.mb-5.mx-5.my-5{data: {likeit_target: 'display'} }
          = render partial: 'animals/display', locals: { animal: animal, user: @current_user }

app/views/home/index.html.haml
.jumbotron.jumbotron-fluid
  .container
    %h1.display-4 Welcome Home
    %p.lead You've made it to the homepage
    %p.lead
      - if @current_user
        And we know that you are #{@current_user.name}
        %br
        = link_to 'Go Pick Animals', animals_path, :class => "btn btn-lg btn-primary"
      - else
        We don't know who you are yet?
        %br
        = form_with(model: User.new, url: users_path, method: :post) do |f|
          = f.label :name
          = f.text_field :name
          = f.submit "Sign Up"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Stimulus Cards Example
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield